import { db } from '../db/config';
import { cities } from '../db/schema';
import dotenv from 'dotenv';
import { v4 as uuidv4 } from 'uuid';

dotenv.config();

const newCities = [
  {
    id: uuidv4(),
    name: 'Rio de Janeiro',
    country: 'Brazil',
    continent: 'South America',
    description: 'The birthplace of BJJ with the highest concentration of black belts and legendary academies.',
    image: 'https://images.pexels.com/photos/2868242/pexels-photo-2868242.jpeg',
    coordinates: '(-43.1729,-22.9068)',
    featured: true,
    gym_density: '10',
    belt_friendliness: '10',
    instructor_quality: '10',
    drop_in_friendliness: '8',
    competition_opportunities: '10',
    monthly_cost: '100',
    cost_of_living: '5',
    visa_friendliness: '7',
    safety: '6',
    english_friendly: false,
    weather_type: 'tropical',
    weather_score: '8',
    healthcare: '7',
    bjj_community: '10',
    social_life: '9',
    recovery_facilities: true,
    remote_work_friendly: true,
    wifi_speed: '30',
    coworking_spaces: true
  },
  {
    id: uuidv4(),
    name: 'San Diego',
    country: 'USA',
    continent: 'North America',
    description: 'A major hub for BJJ in the US with many world-class academies and perfect weather.',
    image: 'https://images.pexels.com/photos/2868242/pexels-photo-2868242.jpeg',
    coordinates: '(-117.1611,32.7157)',
    featured: true,
    gym_density: '9',
    belt_friendliness: '9',
    instructor_quality: '9',
    drop_in_friendliness: '9',
    competition_opportunities: '9',
    monthly_cost: '200',
    cost_of_living: '8',
    visa_friendliness: '9',
    safety: '9',
    english_friendly: true,
    weather_type: 'mediterranean',
    weather_score: '10',
    healthcare: '9',
    bjj_community: '9',
    social_life: '8',
    recovery_facilities: true,
    remote_work_friendly: true,
    wifi_speed: '100',
    coworking_spaces: true
  },
  {
    id: uuidv4(),
    name: 'Tokyo',
    country: 'Japan',
    continent: 'Asia',
    description: 'Home to some of the most technical BJJ and a strong competition scene.',
    image: 'https://images.pexels.com/photos/2868242/pexels-photo-2868242.jpeg',
    coordinates: '(139.6503,35.6762)',
    featured: true,
    gym_density: '8',
    belt_friendliness: '8',
    instructor_quality: '9',
    drop_in_friendliness: '7',
    competition_opportunities: '8',
    monthly_cost: '150',
    cost_of_living: '9',
    visa_friendliness: '6',
    safety: '10',
    english_friendly: false,
    weather_type: 'temperate',
    weather_score: '7',
    healthcare: '10',
    bjj_community: '8',
    social_life: '8',
    recovery_facilities: true,
    remote_work_friendly: true,
    wifi_speed: '200',
    coworking_spaces: true
  },
  {
    id: uuidv4(),
    name: 'Lisbon',
    country: 'Portugal',
    continent: 'Europe',
    description: 'Growing BJJ scene with many high-level competitors and great quality of life.',
    image: 'https://images.pexels.com/photos/2868242/pexels-photo-2868242.jpeg',
    coordinates: '(-9.1393,38.7223)',
    featured: true,
    gym_density: '7',
    belt_friendliness: '8',
    instructor_quality: '8',
    drop_in_friendliness: '9',
    competition_opportunities: '8',
    monthly_cost: '120',
    cost_of_living: '6',
    visa_friendliness: '9',
    safety: '9',
    english_friendly: true,
    weather_type: 'mediterranean',
    weather_score: '9',
    healthcare: '8',
    bjj_community: '8',
    social_life: '9',
    recovery_facilities: true,
    remote_work_friendly: true,
    wifi_speed: '100',
    coworking_spaces: true
  },
  {
    id: uuidv4(),
    name: 'Abu Dhabi',
    country: 'UAE',
    continent: 'Asia',
    description: 'Home to the ADCC and a rapidly growing BJJ scene with world-class facilities.',
    image: 'https://images.pexels.com/photos/2868242/pexels-photo-2868242.jpeg',
    coordinates: '(54.3773,24.4539)',
    featured: true,
    gym_density: '7',
    belt_friendliness: '8',
    instructor_quality: '9',
    drop_in_friendliness: '8',
    competition_opportunities: '9',
    monthly_cost: '180',
    cost_of_living: '9',
    visa_friendliness: '8',
    safety: '10',
    english_friendly: true,
    weather_type: 'desert',
    weather_score: '6',
    healthcare: '9',
    bjj_community: '8',
    social_life: '8',
    recovery_facilities: true,
    remote_work_friendly: true,
    wifi_speed: '200',
    coworking_spaces: true
  },
  {
    id: uuidv4(),
    name: 'Los Angeles',
    country: 'USA',
    continent: 'North America',
    description: 'Major BJJ hub with many famous academies and regular competitions.',
    image: 'https://images.pexels.com/photos/2868242/pexels-photo-2868242.jpeg',
    coordinates: '(-118.2437,34.0522)',
    featured: true,
    gym_density: '9',
    belt_friendliness: '9',
    instructor_quality: '9',
    drop_in_friendliness: '8',
    competition_opportunities: '9',
    monthly_cost: '200',
    cost_of_living: '7',
    visa_friendliness: '9',
    safety: '8',
    english_friendly: true,
    weather_type: 'mediterranean',
    weather_score: '9',
    healthcare: '8',
    bjj_community: '9',
    social_life: '9',
    recovery_facilities: true,
    remote_work_friendly: true,
    wifi_speed: '100',
    coworking_spaces: true
  },
  {
    id: uuidv4(),
    name: 'Amsterdam',
    country: 'Netherlands',
    continent: 'Europe',
    description: 'Strong grappling culture with high-level instruction and great facilities.',
    image: 'https://images.pexels.com/photos/2868242/pexels-photo-2868242.jpeg',
    coordinates: '(4.9041,52.3676)',
    featured: true,
    gym_density: '7',
    belt_friendliness: '8',
    instructor_quality: '8',
    drop_in_friendliness: '9',
    competition_opportunities: '7',
    monthly_cost: '150',
    cost_of_living: '8',
    visa_friendliness: '8',
    safety: '9',
    english_friendly: true,
    weather_type: 'temperate',
    weather_score: '7',
    healthcare: '9',
    bjj_community: '8',
    social_life: '9',
    recovery_facilities: true,
    remote_work_friendly: true,
    wifi_speed: '100',
    coworking_spaces: true
  },
  {
    id: uuidv4(),
    name: 'Sydney',
    country: 'Australia',
    continent: 'Oceania',
    description: 'Thriving BJJ community with many high-level black belts and regular competitions.',
    image: 'https://images.pexels.com/photos/2868242/pexels-photo-2868242.jpeg',
    coordinates: '(151.2093,-33.8688)',
    featured: true,
    gym_density: '8',
    belt_friendliness: '8',
    instructor_quality: '8',
    drop_in_friendliness: '9',
    competition_opportunities: '8',
    monthly_cost: '160',
    cost_of_living: '8',
    visa_friendliness: '7',
    safety: '9',
    english_friendly: true,
    weather_type: 'temperate',
    weather_score: '9',
    healthcare: '9',
    bjj_community: '8',
    social_life: '9',
    recovery_facilities: true,
    remote_work_friendly: true,
    wifi_speed: '100',
    coworking_spaces: true
  }
];

async function main() {
  try {
    for (const city of newCities) {
      const result = await db.insert(cities).values(city).returning();
      console.log(`Added city: ${city.name} with ID: ${city.id}`);
    }
    console.log('\n✅ Successfully added all cities!');
  } catch (error) {
    console.error('❌ Error adding cities:', error);
  } finally {
    process.exit();
  }
}

main(); 